import nodemailer from 'nodemailer';

function escapeHtml(value = '') {
  return String(value)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

async function sendMail({ to, replyTo, subject, text, html }) {
  const from = process.env.ACCESS_HUB_MAIL_FROM || process.env.MAIL_FROM || 'hello@swapnilsanap7.com';

  if (process.env.RESEND_API_KEY) {
    const response = await fetch('https://api.resend.com/emails', {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${process.env.RESEND_API_KEY}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({ from: `Swapnil Sanap <${from}>`, to: [to], reply_to: replyTo, subject, text, html }),
    });
    if (!response.ok) throw new Error(`Resend returned ${response.status}`);
    return response.json();
  }

  if (process.env.APPLE_SMTP_USER && process.env.APPLE_SMTP_PASS) {
    const transporter = nodemailer.createTransport({
      host: 'smtp.mail.me.com',
      port: 587,
      secure: false,
      auth: { user: process.env.APPLE_SMTP_USER, pass: process.env.APPLE_SMTP_PASS },
    });
    return transporter.sendMail({ from: `Swapnil Sanap <${from}>`, to, replyTo, subject, text, html });
  }

  throw new Error('Access Hub mail provider is not configured');
}

function emailShell({ eyebrow, heading, body, actionLabel, actionUrl, footer }) {
  const button = actionUrl
    ? `<a href="${escapeHtml(actionUrl)}" style="display:inline-block;background:#0066ff;color:#fff;text-decoration:none;font-weight:700;padding:14px 22px;border-radius:12px;margin-top:10px">${escapeHtml(actionLabel)}</a>`
    : '';

  return `<!doctype html><html><body style="margin:0;background:#eef1f5;color:#122033;font-family:Arial,sans-serif"><table role="presentation" width="100%" cellpadding="0" cellspacing="0"><tr><td align="center" style="padding:32px 16px"><table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="max-width:620px;background:#fff;border:1px solid #dbe2ea;border-radius:20px;overflow:hidden"><tr><td style="height:8px;background:#0066ff"></td></tr><tr><td style="padding:36px"><p style="margin:0 0 12px;color:#0066ff;font-size:12px;font-weight:700;letter-spacing:.14em;text-transform:uppercase">${escapeHtml(eyebrow)}</p><h1 style="margin:0 0 22px;font-size:28px;line-height:1.2">${escapeHtml(heading)}</h1>${body}${button}</td></tr><tr><td style="padding:20px 36px;background:#f7f9fb;color:#64748b;font-size:12px;line-height:1.6">${footer}</td></tr></table></td></tr></table></body></html>`;
}

export async function sendNewRequestNotification(request) {
  const siteUrl = (process.env.NEXT_PUBLIC_SITE_URL || 'https://swapnilsanap7.com').replace(/\/$/, '');
  const reviewUrl = `${siteUrl}/access/admin?request=${encodeURIComponent(request.id)}`;
  const submitted = new Intl.DateTimeFormat('en-US', { dateStyle: 'medium', timeStyle: 'short', timeZone: 'Asia/Kolkata' }).format(new Date(request.created_at));
  const body = `<table role="presentation" width="100%" style="border-collapse:collapse;font-size:14px;line-height:1.6"><tr><td style="padding:7px 0;color:#64748b">Project</td><td style="padding:7px 0;font-weight:700">${escapeHtml(request.project_name)}</td></tr><tr><td style="padding:7px 0;color:#64748b">Name</td><td style="padding:7px 0">${escapeHtml(request.name)}</td></tr><tr><td style="padding:7px 0;color:#64748b">Email</td><td style="padding:7px 0">${escapeHtml(request.email)}</td></tr><tr><td style="padding:7px 0;color:#64748b">Role</td><td style="padding:7px 0">${escapeHtml(request.role)}</td></tr><tr><td style="padding:7px 0;color:#64748b">Submitted</td><td style="padding:7px 0">${escapeHtml(submitted)}</td></tr></table><div style="margin:22px 0;padding:18px;background:#f7f9fb;border-left:4px solid #0066ff;border-radius:10px;white-space:pre-wrap;font-size:14px;line-height:1.6">${escapeHtml(request.reason)}</div>`;

  return sendMail({
    to: process.env.ACCESS_HUB_ADMIN_EMAIL || 'hello@swapnilsanap7.com',
    replyTo: request.email,
    subject: `Demo access request — ${request.project_name}`,
    text: `New access request\n\nProject: ${request.project_name}\nName: ${request.name}\nEmail: ${request.email}\nRole: ${request.role}\nSubmitted: ${submitted}\n\n${request.reason}\n\nReview: ${reviewUrl}`,
    html: emailShell({ eyebrow: 'Project Access Hub', heading: `New request for ${request.project_name}`, body, actionLabel: 'Review request', actionUrl: reviewUrl, footer: 'This notification was generated by the Project Access Hub at swapnilsanap7.com.' }),
  });
}

export async function sendAccessApprovedEmail(request, access) {
  const expiry = request.access_expires_at
    ? new Intl.DateTimeFormat('en-US', { dateStyle: 'long', timeZone: 'UTC' }).format(new Date(request.access_expires_at))
    : null;
  const expiryCopy = expiry ? `<p style="margin:18px 0;color:#475569;line-height:1.65">Your demo access is available until <strong>${escapeHtml(expiry)}</strong>.</p>` : '';
  const instructions = access.instructions ? `<p style="margin:18px 0;color:#475569;line-height:1.65">${escapeHtml(access.instructions)}</p>` : '';
  const body = `<p style="margin:0;color:#475569;line-height:1.65">Hi ${escapeHtml(request.name)},</p><p style="margin:18px 0;color:#475569;line-height:1.65">Your request to explore <strong>${escapeHtml(request.project_name)}</strong> has been approved. Your private demo access is ready.</p>${expiryCopy}${instructions}`;

  return sendMail({
    to: request.email,
    subject: `Your ${request.project_name} demo access is ready`,
    text: `Hi ${request.name},\n\nYour request to explore ${request.project_name} has been approved.${expiry ? ` Access expires ${expiry}.` : ''}\n\nOpen project: ${access.url}`,
    html: emailShell({ eyebrow: 'Access approved', heading: 'Your demo access is ready.', body, actionLabel: 'Open project', actionUrl: access.url, footer: 'You received this email because you requested access through swapnilsanap7.com. Please do not share private demo links or credentials.' }),
  });
}

export async function sendRequestRejectedEmail(request) {
  const body = `<p style="margin:0;color:#475569;line-height:1.65">Hi ${escapeHtml(request.name)},</p><p style="margin:18px 0;color:#475569;line-height:1.65">Thank you for your interest in <strong>${escapeHtml(request.project_name)}</strong>. I’m not able to provide demo access for this request right now.</p><p style="margin:18px 0;color:#475569;line-height:1.65">You’re welcome to explore the public project story and check back later.</p>`;
  const siteUrl = (process.env.NEXT_PUBLIC_SITE_URL || 'https://swapnilsanap7.com').replace(/\/$/, '');
  return sendMail({
    to: request.email,
    subject: `Update on your ${request.project_name} access request`,
    text: `Hi ${request.name},\n\nThank you for your interest in ${request.project_name}. I’m not able to provide demo access for this request right now.`,
    html: emailShell({ eyebrow: 'Request update', heading: 'Thanks for your interest.', body, actionLabel: 'View project story', actionUrl: `${siteUrl}/projects/${request.project_slug}`, footer: 'This is a personal review process. You can reply to this email if you believe important context was missed.' }),
  });
}

